project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
        
  page-footer: 
    right: "&copy; 2024, Stella Koh"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em

editor: visual

execute: 
  freeze: auto
